### ISSUE TITLE
Implement mapping between DSL and actual RabbitMQ invocations

### ISSUE THREAD

**Issue by sergeytrasko** [ctco-dev/cukes-rabbitmq#4]

**Comment by IgorGursky** [comment]
Is there any preferences in the actual implementation of the tool to be used to call/receive from MQs?

**Comment by sergeytrasko** [comment]
Primary candidate would be amqp-client from RabbitMQ - https://www.rabbitmq.com/java-client.html

**Comment by sergeytrasko** [comment]
Ongoing process, initial implementation is completed
